# Generated by Django 5.1.5 on 2025-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='family_name',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
