# Generated by Django 5.1.5 on 2025-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_buyerprofile_family_name_buyerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='zip_code',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
