# Generated by Django 5.1.4 on 2025-01-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent_category', models.CharField(blank=True, choices=[('classic_historic', 'سبک\u200cهای کلاسیک و تاریخی'), ('modern_contemporary', 'سبک\u200cهای مدرن و معاصر'), ('cultural_regional', 'سبک\u200cهای فرهنگی و منطقه\u200cای'), ('abstract_conceptual', 'سبک\u200cهای انتزاعی و مفهومی'), ('specialized_technical', 'سبک\u200cهای تخصصی و تکنیکی'), ('special_new', 'سبک\u200cهای خاص و جدید'), ('subject_based', 'دسته\u200cبندی موضوعی')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
    ]
