# Generated by Django 5.1.4 on 2025-01-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_parent_category_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.CharField(blank=True, choices=[('classic_historic', 'سبک\u200cهای کلاسیک و تاریخی'), ('modern_contemporary', 'سبک\u200cهای مدرن و معاصر'), ('cultural_regional', 'سبک\u200cهای فرهنگی و منطقه\u200cای'), ('abstract_conceptual', 'سبک\u200cهای انتزاعی و مفهومی'), ('specialized_technical', 'سبک\u200cهای تخصصی و تکنیکی'), ('special_new', 'سبک\u200cهای خاص و جدید'), ('subject_based', 'دسته\u200cبندی موضوعی')], max_length=50, null=True),
        ),
    ]
