# Generated by Django 5.1.5 on 2025-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='family_name',
            field=models.CharField(default='seller', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='name',
            field=models.CharField(default='seller', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='melicode',
            field=models.CharField(max_length=10),
        ),
    ]
