# Generated by Django 5.1.5 on 2025-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='zip_code',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
