# Generated by Django 5.1.5 on 2025-02-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_custom_features_product_fast_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
